---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: endpointmonitors.xycrd.thriqon.github.io
spec:
  group: xycrd.thriqon.github.io
  names:
    kind: EndpointMonitor
    plural: endpointmonitors
    shortNames:
      - em
    singular: endpoindmonitor
    categories:
    - all
  scope: Namespaced
  versions:
  - name: v1alpha1
    served: true
    storage: true
    additionalPrinterColumns:
      - jsonPath: .spec.url
        name: URL
        type: string
      - name: Age
        type: date
        jsonPath: .metadata.creationTimestamp
    schema:
      openAPIV3Schema:
        description: "Monitoring for a single endpoint"
        title: EndpointMonitor
        type: object
        required:
          - spec
        properties:
          spec:
            type: object
            properties:
              contentCheck:
                type: string
                nullable: true
              tags:
                type: string
                nullable: true
              url:
                type: string
            required:
            - url
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: endpointmonitors-edit
  labels:
    # Add these permissions to the "admin" and "edit" default roles.
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
rules:
- apiGroups: ["xycrd.thriqon.github.io"]
  resources: ["endpointmonitors"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: endpointmonitors-view
  labels:
    # Add these permissions to the "view" default role.
    rbac.authorization.k8s.io/aggregate-to-view: "true"
rules:
- apiGroups: ["xycrd.thriqon.github.io"]
  resources: ["endpointmonitors"]
  verbs: ["get", "list", "watch"]
