name: CI

on:
  push:
    branches:
      - '*'
  pull_request:
    branches: [ main ]
  release:
    types: # This configuration does not affect the page_build event above
    - created

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install stable toolchain
      uses: actions-rs/toolchain@v1
      with:
          profile: minimal
          toolchain: stable
          override: true
          components: rustfmt, clippy

    - name: Cache Rust Dependencies
      uses: Swatinem/rust-cache@v1
    - name: Run cargo build
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --verbose --release
    - name: Strip Binary
      run: |
        strip target/release/xycrd
    - name: Run cargo test
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --verbose

    - name: Clippy warnings
      uses: actions-rs/clippy-check@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        args: --all-features
    - name: Security audit
      uses: actions-rs/audit-check@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Run cargo fmt
      uses: actions-rs/cargo@v1
      with:
        command: fmt
        args: --all -- --check
        
    - name: NFPM .deb
      uses: blinktag/nfpm@v2.3.1
      with:
        packager: deb
    - name: Prepare location of binary
      run: mv target/release/xycrd .
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.3
      with:
        name: binaries
        path: |
          xycrd*deb
          xycrd

  integration-test-deb:
    strategy:
      matrix:
        node_image:
          - kindest/node:v1.21.2
          - kindest/node:v1.20.2
          - kindest/node:v1.19.7
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Fetch Package
      uses: actions/download-artifact@v2.0.9
      with:
        name: binaries
    - name: Kubernetes KinD Cluster
      uses: container-tools/kind-action@v1
      with:
        wait: 120s
    - name: Run Tests
      run: |
        ./integration-tests.sh

  release:
    needs:
      - integration-test-deb
      - build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
    - name: Fetch Package
      uses: actions/download-artifact@v2.0.9
      with:
        name: binaries
    - name: GH Release
      uses: softprops/action-gh-release@v0.1.5
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        files: |
          xycrd*deb
          xycrd
